# Generated by Django 5.1.4 on 2025-03-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_admin_client_serviceclient_validateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('media', models.FileField(upload_to='tutoriels/')),
            ],
        ),
        migrations.RemoveField(
            model_name='validateur',
            name='autorisation_validation',
        ),
        migrations.AddField(
            model_name='transaction',
            name='achat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.achat'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.vente'),
        ),
        migrations.AlterField(
            model_name='achat',
            name='statut',
            field=models.IntegerField(choices=[('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('En attente', 'En attente')], default='En attente'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='niveau_acces',
            field=models.CharField(default='admin', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='disponible',
            field=models.BooleanField(choices=[('Non', 'Non disponible'), ('Oui', 'Disponible')], default='Oui'),
        ),
        migrations.AlterField(
            model_name='serviceclient',
            name='niveau_acces',
            field=models.CharField(default='service_client', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.IntegerField(choices=[('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('En attente', 'En attente')], default='En attente'),
        ),
        migrations.AlterField(
            model_name='validateur',
            name='niveau_acces',
            field=models.CharField(default='validateur', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='vente',
            name='statut',
            field=models.IntegerField(choices=[('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('En attente', 'En attente')], default='En attente'),
        ),
    ]
