# Generated by Django 5.1.4 on 2025-03-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_crypto_prix_achat_min_crypto_prix_vente_min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='disponible',
            new_name='disponibilite',
        ),
    ]
