# Generated by Django 5.1.4 on 2025-03-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_disponible_crypto_disponibilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='disponibilite',
            field=models.CharField(choices=[('Non', 'Non disponible'), ('Oui', 'Disponible')], default='Oui'),
        ),
    ]
