# Generated by Django 5.1.4 on 2025-06-01 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_crypto_disponibilite'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('cni', models.CharField(blank=True, max_length=20, null=True)),
                ('statut', models.IntegerField(choices=[('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('En attente', 'En attente')], default=0)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='backend.client')),
            ],
        ),
    ]
