# Generated by Django 5.2 on 2025-06-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceclient',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
