# Generated by Django 5.1.4 on 2025-06-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_historique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historique',
        ),
    ]
