# Generated by Django 5.1.4 on 2025-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_delete_historique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='valeur',
        ),
        migrations.AlterField(
            model_name='achat',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
