# Generated by Django 5.1.4 on 2025-06-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_achat_montant_remove_achat_valeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.IntegerField(choices=[(0, 'En attente'), (1, 'Approuvé'), (2, 'Rejeté')], default=0),
        ),
    ]
