# Generated by Django 5.1.4 on 2025-06-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_transaction_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20),
        ),
    ]
