# Generated by Django 5.1.4 on 2025-06-16 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_transaction_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='achat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.achat'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.vente'),
        ),
    ]
