# Generated by Django 5.1.4 on 2025-06-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_client_date_inscription_alter_client_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='statut',
            field=models.CharField(choices=[('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('En attente', 'En attente')], default='En attente'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté'), ('En attente', 'En attente')], default='En attente'),
        ),
    ]
