# Generated by Django 5.1.4 on 2025-06-19 14:11

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_achat_statut_alter_vente_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='document_identite',
            field=models.FileField(blank=True, null=True, upload_to=backend.models.kyc_upload_path),
        ),
        migrations.AddField(
            model_name='kyc',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to=backend.models.kyc_upload_path),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validée'), ('refuse', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
