# Generated by Django 5.2.4 on 2025-07-23 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_kyc_document_identite_kyc_selfie_alter_kyc_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(default='USD', max_length=10)),
                ('currency_to', models.CharField(default='XOF', max_length=10)),
                ('rate', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='crypto',
            name='disponibilite',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Oui'),
        ),
        migrations.CreateModel(
            name='ConversionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_fcfa', models.FloatField()),
                ('amount_crypto', models.FloatField()),
                ('exchange_rate_usd_fcfa', models.FloatField()),
                ('crypto_price_usd', models.FloatField()),
                ('applied_margin_percentage', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.crypto')),
            ],
        ),
    ]
