# Generated by Django 5.2.4 on 2025-07-23 17:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_exchangerate_alter_crypto_disponibilite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crypto',
            options={'verbose_name': 'Cryptomonnaie', 'verbose_name_plural': 'Cryptomonnaies'},
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='disponibilite',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='prix_achat',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='prix_achat_min',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='prix_vente',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='prix_vente_min',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='quantite',
        ),
        migrations.AddField(
            model_name='conversiontransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crypto',
            name='blockchain_address_format',
            field=models.CharField(blank=True, help_text="Ex: Format d'adresse de portefeuille (si pertinent, ex: BEP-20 contract address).", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='buy_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.0'), help_text="Marge appliquée au prix de vente (quand l'utilisateur ACHETE de la crypto chez vous).", max_digits=5),
        ),
        migrations.AddField(
            model_name='crypto',
            name='coingecko_id',
            field=models.CharField(blank=True, help_text="ID sur CoinGecko (ex: 'bitcoin' pour BTC). Laisser vide pour auto-détection par sigle.", max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si la cryptomonnaie est active pour le trading.'),
        ),
        migrations.AddField(
            model_name='crypto',
            name='market_price_usd',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), help_text='Prix actuel de la crypto en USD (à mettre à jour via API).', max_digits=20),
        ),
        migrations.AddField(
            model_name='crypto',
            name='max_transaction_fcfa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant maximum en FCFA pour une transaction (achat/vente).', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='min_transaction_fcfa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant minimum en FCFA pour une transaction (achat/vente).', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='quantite_disponible',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), help_text='Quantité de cette crypto disponible sur votre exchange.', max_digits=20),
        ),
        migrations.AddField(
            model_name='crypto',
            name='sell_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.0'), help_text="Marge appliquée au prix d'achat (quand l'utilisateur VEND de la crypto à vous).", max_digits=5),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='nom',
            field=models.CharField(help_text='Nom complet de la cryptomonnaie (ex: Bitcoin)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='sigle',
            field=models.CharField(help_text='Symbole de la cryptomonnaie (ex: BTC)', max_length=10, unique=True),
        ),
    ]
