# Generated by Django 5.2.4 on 2025-07-23 18:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_crypto_options_remove_crypto_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversiontransaction',
            name='crypto_price_usd',
        ),
        migrations.RemoveField(
            model_name='conversiontransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='coingecko_id',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='max_transaction_fcfa',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='min_transaction_fcfa',
        ),
        migrations.AddField(
            model_name='conversiontransaction',
            name='crypto_price_usd_at_transaction',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversiontransaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Achat'), ('SELL', 'Vente')], default='BUY', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crypto',
            name='max_buy_fcfa',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='crypto',
            name='max_sell_fcfa',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='crypto',
            name='min_buy_fcfa',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='crypto',
            name='min_sell_fcfa',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='conversiontransaction',
            name='amount_crypto',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='conversiontransaction',
            name='amount_fcfa',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='conversiontransaction',
            name='applied_margin_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='conversiontransaction',
            name='exchange_rate_usd_fcfa',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='blockchain_address_format',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='buy_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='market_price_usd',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='quantite_disponible',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='sell_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='sigle',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
