# Generated by Django 5.2.4 on 2025-07-23 18:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_conversiontransaction_crypto_price_usd_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.RenameField(
            model_name='crypto',
            old_name='blockchain_address_format',
            new_name='deposit_address',
        ),
        migrations.RenameField(
            model_name='crypto',
            old_name='max_buy_fcfa',
            new_name='max_achat_fcfa',
        ),
        migrations.RenameField(
            model_name='crypto',
            old_name='max_sell_fcfa',
            new_name='max_vente_fcfa',
        ),
        migrations.RenameField(
            model_name='crypto',
            old_name='min_buy_fcfa',
            new_name='min_achat_fcfa',
        ),
        migrations.RenameField(
            model_name='crypto',
            old_name='min_sell_fcfa',
            new_name='min_vente_fcfa',
        ),
        migrations.RemoveField(
            model_name='conversiontransaction',
            name='applied_margin_percentage',
        ),
        migrations.RemoveField(
            model_name='conversiontransaction',
            name='crypto_price_usd_at_transaction',
        ),
        migrations.RemoveField(
            model_name='conversiontransaction',
            name='exchange_rate_usd_fcfa',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='buy_margin_percentage',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='market_price_usd',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='sell_margin_percentage',
        ),
        migrations.AddField(
            model_name='crypto',
            name='valeur_sur_le_marche_fcfa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='conversiontransaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Achat'), ('SELL', 'Vente')], default='BUY', max_length=4),
        ),
    ]
