# Generated by Django 5.2.4 on 2025-07-23 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_delete_exchangerate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crypto',
            options={},
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='is_active',
        ),
        migrations.AddField(
            model_name='conversiontransaction',
            name='fedapay_transaction_id',
            field=models.CharField(blank=True, help_text='ID de transaction FedaPay', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='conversiontransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de paiement'), ('PAID', 'Payé (Attente confirmation crypto)'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('COMPLETED', 'Terminé (Crypto envoyée)'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='conversiontransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversiontransaction',
            name='user_paying_address',
            field=models.CharField(blank=True, help_text="Adresse d'où l'utilisateur envoie la crypto (pour les ventes)", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conversiontransaction',
            name='user_receiving_address',
            field=models.CharField(blank=True, help_text="Adresse où l'utilisateur recevra la crypto (pour les achats)", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crypto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crypto_images/'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='deposit_address',
            field=models.CharField(blank=True, help_text='Adresse de dépôt pour cette crypto (pour les ventes)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='min_achat_fcfa',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=15),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='min_vente_fcfa',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=15),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='sigle',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='AdresseCrypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.crypto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'crypto', 'adresse')},
            },
        ),
    ]
